clone_depth: 5

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      QTDIR: "C:/Qt/5.3/msvc2013_opengl/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.3/msvc2013_opengl/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside_Qt5.3_x86.zip

install:
  - set PATH=%PATH%;%QTDIR%

build_script:
  - mkdir build && cd build
  - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%
  - cmake --build . --config %CONFIGURATION%
  - cd ..

test_script:
  - build\test\%CONFIGURATION%\TestDynamicQObject.exe

after_build:
  - 7z a %ARTIFACT% build\lib\%CONFIGURATION%\DOtherSide.dll README.md CHANGELOG.md LICENSE

artifacts:
  - path: $(ARTIFACT)
    name: $(ARTIFACT)
    type: zip

deploy:
  description: 'My description'
  provider: GitHub
  auth_token:
    secure: Brw9CAHN/fULjHQtbrG8jlFkfQcj7NjEWUvUkRB0vrJP2T9glct2Zsrv0lE3H833
  artifact: $(ARTIFACT)
