environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      MSYS_BITS: 32
      QTDIR: C:\Qt\5.5\mingw492_32
    - TARGET: x86_64-pc-windows-msvc
      QTDIR: C:\Qt\5.5\msvc2013_64
    - TARGET: i686-pc-windows-msvc
      QTDIR: C:\Qt\5.5\msvc2013
    
build_script:
  - mkdir build
  - cd build
  - echo %PATH%
  - echo %QTDIR%
  - echo %TARGET%
  - SET PATH=%PATH%;%QTDIR%
  - cmake ..
