environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      MSYS_BITS: 64
    - TARGET: i686-pc-windows-gnu
      MSYS_BITS: 32
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc
    
build_script:
  cd build
  cmake ..
