clone_depth: 5

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      CMAKE_PREFIX_PATH: C:/Qt/5.3/msvc2013_opengl
      CONFIGURATION: Release
    - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      CMAKE_PREFIX_PATH: C:/Qt/5.3/msvc2013_64_opengl
      CONFIGURATION: Release

build_script:
  - mkdir build && cd build
  - cmake .. -G"%CMAKE_GENERATOR%"
  - cmake --build . --config %CONFIGURATION%
