clone_depth: 5

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      QTDIR: "C:/Qt/5.3/msvc2013_opengl/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.3/msvc2013_opengl/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside-windows-x86-msvc2013-qt-5.3.zip
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      QTDIR: "C:/Qt/5.3/msvc2013_64_opengl/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.3/msvc2013_64_opengl/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside-windows-x64-msvc2013-Qt5.3.zip
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      QTDIR: "C:/Qt/5.4/msvc2013_opengl/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.4/msvc2013_opengl/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside-windows-x86-msvc2013-qt-5.4.zip
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      QTDIR: "C:/Qt/5.4/msvc2013_64_opengl/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.4/msvc2013_64_opengl/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside-windows-x64-msvc2013-Qt5.4.zip
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      QTDIR: "C:/Qt/5.5/msvc2013/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.5/msvc2013/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside-windows-x86-msvc2013-qt-5.5.zip
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      QTDIR: "C:/Qt/5.5/msvc2013_64/bin"
      CMAKE_PREFIX_PATH: "C:/Qt/5.5/msvc2013_64/lib/cmake"
      CONFIGURATION: Release
      ARTIFACT: libDOtherside-windows-x64-msvc2013-Qt5.5.zip

install:
  - set PATH=%PATH%;%QTDIR%

build_script:
  - mkdir build && cd build
  - cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%
  - cmake --build . --config %CONFIGURATION%
  - cd ..

test_script:
  - build\test\%CONFIGURATION%\TestDynamicQObject.exe

after_build:
  - 7z a %ARTIFACT% %APPVEYOR_BUILD_FOLDER%\build\lib\%CONFIGURATION%\DOtherSide.dll README.md CHANGELOG.md LICENSE

artifacts:
  - path: $(ARTIFACT)
    name: $(ARTIFACT)
    type: zip

deploy:
  description: 'My description'
  provider: GitHub
  auth_token:
    secure: Brw9CAHN/fULjHQtbrG8jlFkfQcj7NjEWUvUkRB0vrJP2T9glct2Zsrv0lE3H833
  artifact: $(ARTIFACT)
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
